<package format="2">
  <name>aliengo_commons</name>
  <version>1.0.0</version>
  <description>
    aliengo-commons.
    Based on hyq-commons and hyqreal-commons
  </description>
  <maintainer email="domingo.esteban@iit.it">Domingo Esteban</maintainer>
  <license>BSD</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>iit_commons</depend>

  <test_depend>rostest</test_depend>

</package>
