struct DebugPinocchio
{
    double q_inv_kin_gt[19]; // joints configuration
    double q_inv_kin[19]; // joints configuration
    double q_inv_kin_robotlib[12];

    double err_inv_kin[6];
    double q_init_guess[19]; // joints configuration

    double ee_pose_des[6]; //pos, rpy
    double ee_pose[6]; //pos, rpy
    double ee_parent_joint_pose_des[6]; //pos, rpy

    double tau_gt[12]; 
    double tau_est[12]; 

    double qd_inv_diff_kin_robotlib[12];
    double qd_gt[12];
};